// src/shared/components/Navbar.vue
<template>
  <section
    class="bg-glass bg-base-100 shadow-sm glass-border-b w-full fixed top-0 z-1"
  >
    <div class="navbar text-desc max-w-7xl m-auto">
      <div class="navbar-start flex-grow py-0">
        <div class="dropdown">
          <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
            <img
              src="/icons/menu-icon.svg"
              alt="Menu"
              class="invert w-7 h-7"
            />
          </div>
          <ul
            tabindex="0"
            class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow bg-default rounded-lg"
          >
            <li><router-link active-class="bg-active-blue" to="/" class="rounded-xl text-base">Inicio</router-link></li>
            <li><span active-class="bg-active-blue" to="#" class="rounded-xl text-base">Proyectos</span></li>
            <li><router-link active-class="bg-active-blue" to="/resources" class="rounded-xl text-base">Recursos</router-link></li>
            <li><router-link active-class="bg-active-blue" to="/contact" class="rounded-xl text-base">Contacto</router-link></li>
          </ul>
        </div>
        <router-link to="/" class="text-xl text-cian font-bold">RDC</router-link>
      </div>
      <div class="navbar-center hidden lg:flex pt-0">
        <ul class="menu menu-horizontal px-1 gap-5">
          <li><router-link active-class="bg-active-blue" to="/" class="rounded-xl text-base">Inicio</router-link></li>
          <li><span active-class="bg-active-blue" to="#" class="rounded-xl text-base">Proyectos</span></li>
          <li><router-link active-class="bg-active-blue" to="/resources" class="rounded-xl text-base">Recursos</router-link></li>
          <li><router-link active-class="bg-active-blue" to="/contact" class="rounded-xl text-base">Contacto</router-link></li>
        </ul>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts"></script>

<style scoped>
.menu a,
.menu summary {
  transition: 300ms;
}
.menu a:hover,
.menu summary:hover {
  background-color: var(--custom-light-bg);
}
.navbar {
  padding: 5px 2rem;
}
</style>

// src/ui/shared/components/Navbar/Navbar.tsx
import type { FC } from "react";
import { NavLink } from "react-router";
import "./Navbar.css";

export const Navbar: FC = () => {
  return (
    <>
      <section className="bg-glass bg-base-100 shadow-sm glass-border-b w-full fixed top-0 z-10">
        <div className="navbar text-desc max-w-7xl m-auto">
          <div className="navbar-start grow py-0">
            <div className="dropdown">
              <div role="button" className="btn btn-ghost lg:hidden">
                <img src="/icons/menu-icon.svg" alt="Menu" className="invert w-7 h-7" />
              </div>
              <ul className="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow bg-default rounded-lg">
                <li>
                  <NavLink to="/" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                    Inicio
                  </NavLink>
                </li>
                {/* <li>
                  <NavLink to="#" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                    Proyectos
                  </NavLink>
                </li> */}
                <li>
                  <NavLink
                    to="/resources"
                    className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}
                  >
                    Recursos
                  </NavLink>
                </li>
                <li>
                  <NavLink to="/contact" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                    Contacto
                  </NavLink>
                </li>
              </ul>
            </div>
            <NavLink to="/" className="text-xl text-cian font-bold">
                RDC
            </NavLink>
          </div>
          <div className="navbar-center hidden lg:flex pt-0">
            <ul className="menu menu-horizontal px-1 gap-5">
              <li>
                <NavLink to="/" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                  Inicio
                </NavLink>
              </li>
              {/* <li>
                <NavLink to="#" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                  Proyectos
                </NavLink>
              </li> */}
              <li>
                <NavLink to="/resources" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                  Recursos
                </NavLink>
              </li>
              <li>
                <NavLink to="/contact" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                  Contacto
                </NavLink>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </>
  );
};
