// src/ui/shared/components/Navbar/Navbar.tsx
import type { FC } from "react";
import { NavLink } from "react-router";
import "./Navbar.css";

export const Navbar: FC = () => {
  return (
    <>
      <section className="bg-glass bg-base-100 shadow-sm glass-border-b w-full fixed top-0 z-10">
        <div className="navbar text-desc max-w-7xl m-auto">
          <div className="navbar-start grow py-0">
            {/* Movil */}
            <div className="dropdown">
              <div role="button" tabIndex={0} className="btn btn-ghost lg:hidden">
                <img src="/icons/menu-icon.svg" alt="Menu" className="invert w-7 h-7" />
              </div>
              <ul tabIndex={0} className="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow bg-default rounded-lg">
                <li>
                  <NavLink to="/" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                    Inicio
                  </NavLink>
                </li>
                {/* <li>
                  <NavLink to="#" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                    Proyectos
                  </NavLink>
                </li> */}
                <li>
                  <NavLink
                    to="/resources"
                    className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}
                  >
                    Recursos
                  </NavLink>
                </li>
                <li>
                  <NavLink to="/contact" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                    Contacto
                  </NavLink>
                </li>
              </ul>
            </div>
            <NavLink to="/" className="text-xl text-cian font-bold">
                RDC
            </NavLink>
          </div>
          
          {/* Desktop */}
          <div className="navbar-center hidden lg:flex pt-0">
            <ul className="menu menu-horizontal px-1 gap-5">
              <li>
                <NavLink to="/" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                  Inicio
                </NavLink>
              </li>
              {/* <li>
                <NavLink to="#" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                  Proyectos
                </NavLink>
              </li> */}
              <li>
                <NavLink to="/resources" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                  Recursos
                </NavLink>
              </li>
              <li>
                <NavLink to="/contact" className={({ isActive }) => (isActive ? "bg-active-blue " : "") + "rounded-xl text-base"}>
                  Contacto
                </NavLink>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </>
  );
};

// src/components/Navbar.vue
<template>
  <div
    class="navbar bg-base-100 shadow-sm glass-border-b top-0 bg-glass font-light fixed"
  >
    <div class="navbar-start flex-grow">
      <div class="dropdown">
        <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M4 6h16M4 12h8m-8 6h16"
            />
          </svg>
        </div>
        <ul
          tabindex="0"
          class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow bg-default rounded-r-xl"
        >
          <li class="text-base"><a>Inicio</a></li>
          <li class="text-base">
            <a>Recursos</a>
            <ul class="p-2">
              <li class="text-base"><a>Graficos</a></li>
              <li class="text-base"><a>Documentación</a></li>
            </ul>
          </li>
          <li class="text-base"><a>Contacto</a></li>
        </ul>
      </div>
      <a class="btn btn-ghost text-2xl text-cian">RDC</a>
    </div>
    <div class="navbar-center hidden lg:flex">
      <ul class="menu menu-horizontal px-1">
        <li class="text-base"><a>Inicio</a></li>
        <li class="text-base">
          <details>
            <summary>Recursos</summary>
            <ul class="p-2">
              <li class="text-base"><a>Graficos</a></li>
              <li class="text-base"><a>Documentación</a></li>
            </ul>
          </details>
        </li>
        <li class="text-base"><a>Contacto</a></li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts"></script>

<style scoped>
.menu a,
.menu summary {
  color: var(--custom-text-desc);
  transition: 300ms;
}
.menu a:hover {
    transform: scale(1.05);
}
</style>
