// src/ui/resources/components/CategoryFilters.vue
<template>
  <div class="flex gap-2 flex-wrap justify-center">
    <button
      v-for="filter in filters"
      @click="selectFilter(filter)"
      :key="filter"
      class="filter-chip glass-border-full rounded-4xl px-4 py-0.5 text-desc cursor-pointer capitalize"
      :class="{ 'filter-chip-active': selectedFilter === filter }"
    >
      {{ filter }}
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

const props = defineProps<{ filters: string[] }>();
const emit = defineEmits(['filter-selected'])

const selectedFilter = ref("");

const selectFilter = (filter: string) => {
  if (selectedFilter.value == filter) {
    selectedFilter.value = "";
  } else {
    selectedFilter.value = filter;
  }
  emit('filter-selected', selectedFilter.value)
};
</script>

<style scoped></style>

// src/ui/resources/components/CategoryFilters/CategoryFilters.tsx
import { useState, useEffect, type FC } from "react";

interface CategoryFiltersProps {
  filters: string[];
  onFilterSelected: (value: string) => void;
}

export const CategoryFilters: FC<CategoryFiltersProps> = ({ filters, onFilterSelected }: CategoryFiltersProps) => {
  const [selectedFilter, setSelectedFilter] = useState("");

  const selectFilter = (filter: string) => {
    setSelectedFilter((prev) => (prev === filter ? "" : filter));
  };

  useEffect(() => {
    onFilterSelected(selectedFilter);
  }, [selectedFilter, onFilterSelected]);

  return (
    <div className="flex gap-2 flex-wrap justify-center">
      {filters.map((filter) => (
        <button
          onClick={() => selectFilter(filter)}
          key={filter}
          className={`filter-chip glass-border-full rounded-4xl px-4 py-0.5 text-desc cursor-pointer capitalize 
            ${selectedFilter === filter ? "filter-chip-active" : ""}`}
        >
          {filter}
        </button>
      ))}
    </div>
  );
};
