// src/ui/resources/components/ResourceCard/ResourceCard.tsx
import type { FC } from "react";
import type { Resource } from "@/domain/shared/interfaces/resource.interface";
import externalLink from "/icons/external-link.svg";
import "./ResourceCard.css";

interface ResourceCardProps {
  resource: Resource;
}

export const ResourceCard: FC<ResourceCardProps> = ({ resource }: ResourceCardProps) => {
  return (
    <div
      className="p-4 py-5 w-1/4 max-w-112.5 min-w-75
        glass-border-full rounded-xl bg-soft-blue 
        flex flex-col grow relative gap-3 justify-between"
    >
      <a href={resource.pageLink} target="_blank" className="external-link w-6 h-6 absolute">
        <img src={externalLink} alt="Visit" className="w-full" />
      </a>

      <h1 className="text-white text-xl font-semibold">{resource.pageName}</h1>
      <p className="text-desc">{resource.description}</p>
      <ul className="flex flex-wrap text-sm gap-2">
        {resource.tags.map((tag) => (
          <li
            className="bg-purple text-purple border-purple font-light rounded-full p-1 px-3 capitalize"
            key={tag + resource.pageName}
          >
            {tag}
          </li>
        ))}
      </ul>
      <p className="text-desc capitalize">{resource.category}</p>
    </div>
  );
};

// src/ui/resources/components/ResourceCard.vue
<template>
  <div
    class="p-4 py-5 w-1/4 max-w-[450px] min-w-[300px] 
    glass-border-full rounded-xl bg-soft-blue 
    flex flex-col flex-grow relative gap-3 justify-between"
  >
    <a :href="props.resource.pageLink" target="_blank" class="external-link w-6 h-6 absolute">
      <img :src="externalLink" alt="Visit" class="w-full" />
    </a>

    <h1 class="text-white text-xl font-semibold">{{ props.resource.pageName }}</h1>
    <p class="text-desc">{{ props.resource.description }}</p>
    <ul class="flex flex-wrap text-sm gap-2">
      <li
        v-for="t in props.resource.tags"
        class="bg-purple text-purple border-purple font-light rounded-full p-1 px-3 capitalize"
      >
        {{ t }}
      </li>
    </ul>
    <p class="text-desc capitalize">{{ props.resource.category }}</p>
  </div>
</template>

<script setup lang="ts">
import type { Resource } from "../../../shared/interfaces/resource.interface";
import externalLink from "/icons/external-link.svg";
const props = defineProps<{ resource: Resource }>();
</script>

<style scoped>
.external-link {
  top: 17px;
  right: 17px;
  transition: 150ms;
  filter: brightness(65%);
}
.external-link:hover {
  top: 14px;
  right: 14px;
  filter: brightness(85%);
}
</style>
